# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ykiprenk <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/06/22 17:49:54 by ykiprenk          #+#    #+#              #
#    Updated: 2024/06/22 20:24:44 by ykiprenk         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
CC=cc
CFLAGS=-Wall -Wextra -Werror
SRCS_DIR=srcs

all:
	$(CC) $(CFLAGS) -c $(SRCS_DIR)/ft_putchar.c -o $(SRCS_DIR)/ft_putchar.o \
	       	-c $(SRCS_DIR)/ft_swap.c \
		-c $(SRCS_DIR)/ft_putstr.c \
		-c $(SRCS_DIR)/ft_strlen.c \
		-c $(SRCS_DIR)/ft_strcmp.c

libft.:

clean:

fclean:

re:

